#include "hcsr04.h"
#include "stm32f4xx_hal.h"
#include "cmsis_os.h"
#include "main.h" // For HCSR04_TRIG_GPIO_Port, HCSR04_TRIG_Pin if generated by CubeMX

#define HCSR04_TIMEOUT_MS 30U

extern TIM_HandleTypeDef htim2;

static volatile HCSR04_State hcsr04_state = HCSR04_STATE_IDLE;
static volatile uint32_t hcsr04_rising_capture = 0;
static volatile uint32_t hcsr04_pulse_width_us = 0;
static volatile uint8_t hcsr04_measurement_ready = 0;
static volatile uint8_t hcsr04_measurement_in_progress = 0;
static uint32_t hcsr04_start_tick = 0;

static void HCSR04_TriggerPulse(void)
{
    uint32_t start;

    HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port,
                      HCSR04_TRIG_Pin,
                      GPIO_PIN_RESET);

    start = TIM2->CNT;
    while ((uint32_t)(TIM2->CNT - start) < 2U)
    {
    }

    HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port,
                      HCSR04_TRIG_Pin,
                      GPIO_PIN_SET);

    start = TIM2->CNT;
    while ((uint32_t)(TIM2->CNT - start) < 10U)
    {
    }

    HAL_GPIO_WritePin(HCSR04_TRIG_GPIO_Port,
                      HCSR04_TRIG_Pin,
                      GPIO_PIN_RESET);
}

bool HCSR04_StartMeasurement(void)
{
    if (hcsr04_measurement_in_progress != 0U)
    {
        return false;
    }

    uint32_t primask = __get_PRIMASK();
    __disable_irq();

    if (hcsr04_measurement_in_progress != 0U)
    {
        if (primask == 0U)
        {
            __enable_irq();
        }
        return false;
    }

    hcsr04_measurement_in_progress = 1U;
    hcsr04_measurement_ready = 0U;
    hcsr04_state = HCSR04_STATE_WAIT_RISING;
    
    __HAL_TIM_SET_CAPTUREPOLARITY(&htim2, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_RISING);

    if (primask == 0U)
    {
        __enable_irq();
    }

    hcsr04_start_tick = osKernelGetTickCount();
    HCSR04_TriggerPulse();

    return true;
}

bool HCSR04_GetResult(HCSR04_Result *result)
{
    if (result == NULL)
    {
        return false;
    }

    if (hcsr04_measurement_ready == 0U)
    {
        return false;
    }

    uint32_t primask = __get_PRIMASK();
    __disable_irq();

    if (hcsr04_measurement_ready == 0U)
    {
        if (primask == 0U)
        {
            __enable_irq();
        }
        return false;
    }

    uint32_t pulse_us = hcsr04_pulse_width_us;
    HCSR04_State state = hcsr04_state;
    hcsr04_measurement_ready = 0U;

    if (primask == 0U)
    {
        __enable_irq();
    }

    result->pulse_width_us = pulse_us;

    if (state == HCSR04_STATE_DONE)
    {
        result->distance_mm = ((uint32_t)pulse_us * 10U) / 58U;
        if (result->distance_mm >= 20U && result->distance_mm <= 4000U)
        {
            result->valid = 1U;
        }
        else
        {
            result->valid = 0U;
        }
    }
    else
    {
        result->distance_mm = 0U;
        result->valid = 0U;
    }

    return true;
}

void HCSR04_ProcessTimeout(uint32_t current_tick)
{
    if (hcsr04_measurement_in_progress != 0U && (current_tick - hcsr04_start_tick) >= HCSR04_TIMEOUT_MS)
    {
        uint32_t primask = __get_PRIMASK();
        __disable_irq();
        
        if (hcsr04_measurement_in_progress != 0U &&
            (hcsr04_state == HCSR04_STATE_WAIT_RISING || hcsr04_state == HCSR04_STATE_WAIT_FALLING) &&
            (current_tick - hcsr04_start_tick) >= HCSR04_TIMEOUT_MS)
        {
            hcsr04_state = HCSR04_STATE_TIMEOUT;
            hcsr04_measurement_in_progress = 0U;
            hcsr04_measurement_ready = 1U;
            hcsr04_pulse_width_us = 0U;
            
            __HAL_TIM_SET_CAPTUREPOLARITY(&htim2, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_RISING);
        }
        
        if (primask == 0U)
        {
            __enable_irq();
        }
    }
}

void HAL_TIM_IC_CaptureCallback(TIM_HandleTypeDef *htim)
{
    if ((htim->Instance != TIM2) ||
        (htim->Channel != HAL_TIM_ACTIVE_CHANNEL_1))
    {
        return;
    }

    if (hcsr04_state == HCSR04_STATE_WAIT_RISING)
    {
        hcsr04_rising_capture = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);
        __HAL_TIM_SET_CAPTUREPOLARITY(htim, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_FALLING);
        hcsr04_state = HCSR04_STATE_WAIT_FALLING;
    }
    else if (hcsr04_state == HCSR04_STATE_WAIT_FALLING)
    {
        uint32_t falling_capture = HAL_TIM_ReadCapturedValue(htim, TIM_CHANNEL_1);
        
        hcsr04_pulse_width_us = (uint32_t)(falling_capture - hcsr04_rising_capture);
        
        __HAL_TIM_SET_CAPTUREPOLARITY(htim, TIM_CHANNEL_1, TIM_INPUTCHANNELPOLARITY_RISING);
        hcsr04_state = HCSR04_STATE_DONE;
        hcsr04_measurement_in_progress = 0U;
        hcsr04_measurement_ready = 1U;
    }
}
